export const sources = [
    { name: '1 Brühe 100 Suppen' },
    { name: 'ala Linde!' },
    { name: 'blau' },
    { name: 'cabeza' },
    { name: 'Claudi' },
    { name: 'Compi / Ordner' },
    { name: 'compi' },
    { name: 'Compi, oder Inae' },
    { name: 'Compi/ Ordner' },
    { name: 'Computer/Ordner' },
    { name: 'Cori/ Ordner' },
    { name: 'Cori´s Dr. Oetker/ Ordner' },
    { name: 'das Gelbe von Gu' },
    { name: 'Della Fantasia' },
    { name: 'Dorte' },
    { name: 'Essenund trinken Rintopf' },
    { name: 'Feye' },
    { name: 'Fisch Dr. Oetker' },
    { name: 'Fisch, Dr. Oetker' },
    { name: 'Für Sie ' },
    { name: 'Für Sie' },
    { name: 'Gu - Eintöpfe' },
    { name: 'GU Laura' },
    { name: 'Heidi / Ordner' },
    { name: 'herzhafte Eintöpfe' },
    { name: 'Hirn' },
    { name: 'Inae' },
    { name: 'Jan / Ordner' },
    { name: 'Keativkühe Suppe' },
    { name: 'Kopf' },
    { name: 'kopf, kreativ' },
    { name: 'Kosi' },
    { name: 'Kreativ / Suppe' },
    { name: 'Kreativ / Suppen' },
    { name: 'kreativ Küche' },
    { name: 'Kreativ' },
    { name: 'KreativKüche' },
    { name: 'Laur´s Gu' },
    { name: 'Laura GU' },
    { name: 'Laura Melli' },
    { name: 'Laura silber' },
    { name: 'Laura' },
    { name: 'Laura, silber' },
    { name: 'Laura´ Gu' },
    { name: 'Laura´s Gu' },
    { name: 'LEON - Ordner' },
    { name: 'LEON (Ordner)' },
    { name: 'LEON- Ordner' },
    { name: 'LEON Ordner' },
    { name: 'Linde' },
    { name: 'Living at Home' },
    { name: 'melli / Ordner' },
    { name: 'melli Hirn' },
    { name: 'melli' },
    { name: 'melli´s Hirn' },
    { name: 'mellis Hirn' },
    { name: 'Nora / kleines Selbstgemachte' },
    { name: 'Nora/ kleines Selbstgemachte' },
    { name: 'oli' },
    { name: 'Oma´s Rezepte' },
    { name: 'ORDNER / COMPI' },
    { name: 'Ordner' },
    { name: 'Ordner/ Kundin' },
    { name: 'Ordner/Chefkoch.de' },
    { name: 'Ordner/Vegan' },
    { name: 'Party-Topf' },
    { name: 'Partytopf' },
    { name: 'Samira / Ordner' },
    { name: 'sibi' },
    { name: 'siehe Butternut im Ordner' },
    { name: 'Silber' },
    { name: 'silber?' },
    { name: 'Souptime' },
    { name: 'Suppen' },
    { name: 'Syrien (Odner)' },
    { name: 'Syrien (Ordner)' },
    { name: 'Syrien / Ordner' },
    { name: 'Thomas' },
    { name: 'Uli / Ordner' },
    { name: 'Uli/ Ordner' },
    { name: 'Ulli/ Ordner' },
    { name: 'veg. Küche / Oetker' },
    { name: 'würzige Eintöpfe' },
    { name: 'Yvonne' },
    { name: 'Zaubersuppen'}
]