const sources = [
    '1 Brühe 100 Suppen',
    'ala Linde!',
    'blau',
    'cabeza',
    'Claudi',
    'Compi / Ordner',
    'compi',
    'Compi, oder Inae',
    'Compi/ Ordner',
    'Computer/Ordner',
    'Cori/ Ordner',
    'Cori´s Dr. Oetker/ Ordner',
    'das Gelbe von Gu',
    'Della Fantasia',
    'Dorte',
    'Essenund trinken Rintopf',
    'Feye',
    'Fisch Dr. Oetker',
    'Fisch, Dr. Oetker',
    'Für Sie ',
    'Für Sie',
    'Gu - Eintöpfe',
    'GU Laura',
    'Heidi / Ordner',
    'herzhafte Eintöpfe',
    'Hirn',
    'Inae',
    'Jan / Ordner',
    'Keativkühe Suppe',
    'Kopf',
    'kopf, kreativ',
    'Kosi',
    'Kreativ / Suppe',
    'Kreativ / Suppen',
    'kreativ Küche',
    'Kreativ',
    'KreativKüche',
    'Laur´s Gu',
    'Laura GU',
    'Laura Melli',
    'Laura silber',
    'Laura',
    'Laura, silber',
    'Laura´ Gu',
    'Laura´s Gu',
    'LEON - Ordner',
    'LEON (Ordner)',
    'LEON- Ordner',
    'LEON Ordner',
    'Linde',
    'Living at Home',
    'melli / Ordner',
    'melli Hirn',
    'melli',
    'melli´s Hirn',
    'mellis Hirn',
    'Nora / kleines Selbstgemachte',
    'Nora/ kleines Selbstgemachte',
    'oli',
    'Oma´s Rezepte',
    'ORDNER / COMPI',
    'Ordner',
    'Ordner/ Kundin',
    'Ordner/Chefkoch.de',
    'Ordner/Vegan',
    'Party-Topf',
    'Partytopf',
    'Samira / Ordner',
    'sibi',
    'siehe Butternut im Ordner',
    'Silber',
    'silber?',
    'Souptime',
    'Suppen',
    'Syrien (Odner)',
    'Syrien (Ordner)',
    'Syrien / Ordner',
    'Thomas',
    'Uli / Ordner',
    'Uli/ Ordner',
    'Ulli/ Ordner',
    'veg. Küche / Oetker',
    'würzige Eintöpfe',
    'Yvonne',
    'Zaubersuppen'
    ]